export const actionType = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  LOAD_COURSES: "LOAD_COURSES",
  LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",
};
